export { default as Navbar } from './Navbar/Navbar';
export { default as LoremIpsum } from './LoremIpsumGenerator/LoremIpsumGenerator';
export { default as Heading  } from './Heading/Heading';
export { default as Subheading  } from './Subheading/Subheading';
export { default as Title } from './Title/Title';
export { default as Footer } from './Footer/Footer';
export { default as ImageSlider } from './ImageSlider/ImageSlider';
export { default as Subtitle } from './Subtitle/Subtitle';
export { default as Modal } from './Modal/Modal';
